name: Run cppcheck
description: Install and run cppcheck with suppressed checkersReport

runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      uses: ./.github/actions/install-linux-deps

    - name: Cache cppcheck
      uses: actions/cache/restore@v4
      id: cache-cppcheck
      with:
        path: cppcheck
        key: cppcheck-${{ env.CPPCHECK_VER }}

    - name: Build cppcheck
      shell: bash
      if: steps.cache-cppcheck.outputs.cache-hit != 'true'
      run: |
        bash ./scripts/build_cppcheck.sh -v "${CPPCHECK_VER}"

    - name: Save cppcheck cache
      uses: actions/cache/save@v4
      if: steps.cache-cppcheck.outputs.cache-hit != 'true'
      with:
        path: cppcheck
        key: cppcheck-${{ env.CPPCHECK_VER }}

    - name: Install cppcheck
      shell: bash
      run: |
        cd cppcheck
        sudo cmake --install build

    # The flag CMAKE_EXPORT_COMPILE_COMMANDS generates compile_commands.json
    # which is used by cppcheck and clang-tidy
    - name: Configure CMake
      uses: ./.github/actions/configure-cmake
      with:
        custom_flags: "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

    - name: Cppcheck
      shell: bash
      run: |
        set -euo pipefail

        # Locate compile_commands.json
        BUILD_DIR="${BUILD_DIR:-build}"
        if [ ! -f "$BUILD_DIR/compile_commands.json" ]; then
          ALT="$(ls -d cmake-build-* 2>/dev/null | head -n1 || true)"
          if [ -n "$ALT" ] && [ -f "$ALT/compile_commands.json" ]; then
            BUILD_DIR="$ALT"
          fi
        fi
        echo "Using compile_commands.json from: $BUILD_DIR"

        cppcheck \
          --project="$BUILD_DIR/compile_commands.json" \
          --enable=all \
          --inline-suppr \
          --error-exitcode=1 \
          --template=gcc \
          --platform=unix64 -D__linux__ -Dlinux \
          --suppress=missingIncludeSystem \
          --suppress=checkersReport \
          --suppress=normalCheckLevelMaxBranches \
          -i build/_deps \